"""create olist tables

Revision ID: ad4800dd0318
Revises: 
Create Date: 2026-04-30 12:12:56.415857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad4800dd0318'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('customer_unique_id', sa.String(length=64), nullable=False),
    sa.Column('customer_zip_code_prefix', sa.Integer(), nullable=True),
    sa.Column('customer_city', sa.String(length=120), nullable=True),
    sa.Column('customer_state', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_customers_customer_unique_id'), 'customers', ['customer_unique_id'], unique=False)
    op.create_table('product_category_name_translation',
    sa.Column('product_category_name', sa.String(length=120), nullable=False),
    sa.Column('product_category_name_english', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('product_category_name')
    )
    op.create_table('products',
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('product_category_name', sa.String(length=120), nullable=True),
    sa.Column('product_name_lenght', sa.Integer(), nullable=True),
    sa.Column('product_description_lenght', sa.Integer(), nullable=True),
    sa.Column('product_photos_qty', sa.Integer(), nullable=True),
    sa.Column('product_weight_g', sa.Integer(), nullable=True),
    sa.Column('product_length_cm', sa.Integer(), nullable=True),
    sa.Column('product_height_cm', sa.Integer(), nullable=True),
    sa.Column('product_width_cm', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('sellers',
    sa.Column('seller_id', sa.String(length=64), nullable=False),
    sa.Column('seller_zip_code_prefix', sa.Integer(), nullable=True),
    sa.Column('seller_city', sa.String(length=120), nullable=True),
    sa.Column('seller_state', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('seller_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('order_status', sa.String(length=32), nullable=True),
    sa.Column('order_purchase_timestamp', sa.DateTime(), nullable=True),
    sa.Column('order_approved_at', sa.DateTime(), nullable=True),
    sa.Column('order_delivered_carrier_date', sa.DateTime(), nullable=True),
    sa.Column('order_delivered_customer_date', sa.DateTime(), nullable=True),
    sa.Column('order_estimated_delivery_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_order_purchase_timestamp'), 'orders', ['order_purchase_timestamp'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('seller_id', sa.String(length=64), nullable=False),
    sa.Column('shipping_limit_date', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('freight_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.seller_id'], ),
    sa.PrimaryKeyConstraint('order_id', 'order_item_id')
    )
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_order_items_seller_id'), 'order_items', ['seller_id'], unique=False)
    op.create_table('order_payments',
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('payment_sequential', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.String(length=32), nullable=True),
    sa.Column('payment_installments', sa.Integer(), nullable=True),
    sa.Column('payment_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('order_id', 'payment_sequential')
    )
    op.create_table('order_reviews',
    sa.Column('review_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('review_score', sa.Integer(), nullable=True),
    sa.Column('review_comment_title', sa.Text(), nullable=True),
    sa.Column('review_comment_message', sa.Text(), nullable=True),
    sa.Column('review_creation_date', sa.DateTime(), nullable=True),
    sa.Column('review_answer_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_order_reviews_order_id'), 'order_reviews', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_reviews_order_id'), table_name='order_reviews')
    op.drop_table('order_reviews')
    op.drop_table('order_payments')
    op.drop_index(op.f('ix_order_items_seller_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_order_purchase_timestamp'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('sellers')
    op.drop_table('products')
    op.drop_table('product_category_name_translation')
    op.drop_index(op.f('ix_customers_customer_unique_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
